import { useEffect, useState } from "react";
import { FileText, Loader2, UploadCloud } from "lucide-react";
import { downloadMaterial, getMaterials, uploadMaterial } from "../../service/materialService";
import { getProfessorSubjects } from "../../service/professorService";

export default function UploadMaterial() {
    const [subjects, setSubjects] = useState([]);
    const [materials, setMaterials] = useState([]);
    const [subjectId, setSubjectId] = useState("");
    const [file, setFile] = useState(null);
    const [loading, setLoading] = useState(true);
    const [saving, setSaving] = useState(false);
    const [error, setError] = useState("");
    const refresh = async () => { setLoading(true); try { const [subjectData, materialData] = await Promise.all([getProfessorSubjects(), getMaterials()]); setSubjects(subjectData); setMaterials(materialData); setSubjectId((current) => current || (subjectData[0]?.id ? String(subjectData[0].id) : "")); } catch (requestError) { setError(requestError.message || "Unable to load upload form."); } finally { setLoading(false); } };
    useEffect(() => { refresh(); }, []);
    const submit = async (event) => { event.preventDefault(); if (!file) { setError("Choose a file first."); return; } setSaving(true); setError(""); try { const created = await uploadMaterial({ file, subjectId: Number(subjectId) }); setMaterials((current) => [created, ...current]); setFile(null); event.target.reset(); } catch (requestError) { setError(requestError.message || "Unable to upload material."); } finally { setSaving(false); } };
    const download = async (material) => { try { const blob = await downloadMaterial(material.id); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = material.originalFilename || material.title; link.click(); URL.revokeObjectURL(url); } catch (requestError) { setError(requestError.message || "Unable to download material."); } };
    return <section className="space-y-7"><header><h1 className="text-3xl font-extrabold text-slate-900">Upload material</h1><p className="mt-2 text-slate-500">Upload source material for a subject in your teaching workspace.</p></header>{error && <div className="rounded-xl bg-red-50 p-4 text-red-700">{error}</div>}<form onSubmit={submit} className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><label className="block text-sm font-bold text-slate-700">Subject<select required disabled={loading || !subjects.length} value={subjectId} onChange={(event) => setSubjectId(event.target.value)} className="mt-2 block w-full rounded-xl border border-slate-300 p-3">{subjects.map((subject) => <option key={subject.id} value={subject.id}>{subject.name}</option>)}</select></label><label className="mt-5 block rounded-2xl border-2 border-dashed border-orange-200 p-8 text-center"><UploadCloud className="mx-auto text-orange-500" size={34}/><span className="mt-3 block font-bold text-slate-700">Choose a teaching file</span><span className="mt-1 block text-sm text-slate-500">Up to 25 MB</span><input required type="file" onChange={(event) => setFile(event.target.files?.[0] || null)} className="mt-4 block w-full text-sm" /></label><button disabled={saving || loading || !subjects.length} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-orange-500 py-3 font-bold text-white disabled:opacity-60">{saving ? <Loader2 className="animate-spin" /> : <UploadCloud size={18}/>} {saving ? "Uploading…" : "Upload material"}</button></form><article className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><h2 className="text-lg font-bold">Recent materials</h2>{loading ? <Loader2 className="mx-auto my-10 animate-spin text-orange-500"/> : <ul className="mt-4 divide-y divide-slate-100">{materials.map((material) => <li key={material.id} className="flex items-center gap-4 py-4"><FileText className="text-orange-500"/><div className="flex-1"><p className="font-bold text-slate-900">{material.title}</p><p className="text-sm text-slate-500">{material.type} · {material.size} · {material.date}</p></div>{material.originalFilename && <button onClick={() => download(material)} className="rounded-lg px-3 py-2 text-sm font-bold text-orange-600 hover:bg-orange-50">Download</button>}</li>)}{!materials.length && <li className="py-8 text-center text-slate-500">No materials uploaded yet.</li>}</ul>}</article></section>;
}
